TestGetConfiguration should not fail due distro name casing
Or anything that depends on distro.isRegistered()

Well, that's not what happens here:

> go test -tags=gowslmock -run '^TestGetConfiguration$'

--- FAIL: TestGetConfiguration (0.00s)
    --- FAIL: TestGetConfiguration/Success (0.00s)
        distro_test.go:545: Setup: Registering "wsltesting_TestGetConfiguration--Success_9344221188844186837"
        distro_test.go:545: Setup: Distro "wsltesting_TestGetConfiguration--Success_9344221188844186837" registered
        distro_test.go:563:
                Error Trace:    D:/GoWSL/distro_test.go:563
                Error:          Received unexpected error:
                                could not access configuration for WSLTESTING_TESTGETCONFIGURATION--SUCCESS_9344221188844186837: WslGetDistributionConfiguration: failed syscall: not registered
                Test:           TestGetConfiguration/Success
                Messages:       unexpected failure in GetConfiguration
FAIL
exit status 1
FAIL    github.com/ubuntu/gowsl 0.279s