Educated guess about fixing CI error 0x8000000d
CI is showing:

     --- FAIL: TestUninstall/Success_uninstalling_an_Appx-installed_distro (1.95s)
        registration_test.go:409:
            	Error Trace:	C:/Users/wslciuser/actions-runner/_work/GoWSL/GoWSL/registration_test.go:602
            	            				C:/Users/wslciuser/actions-runner/_work/GoWSL/GoWSL/registration_test.go:409
            	Error:      	Received unexpected error:
            	            	exit status 1
            	Test:       	TestUninstall/Success_uninstalling_an_Appx-installed_distro
            	Messages:   	could not register: exit status 1. Stdout: Installing, this may take a few minutes...
            	            	WslRegisterDistribution failed with error: 0x8000000d
            	            	Error: 0x8000000d An illegal state change was requested.

One known reason for that error is a failed install or uninstall leaving leftovers inside the registry.
Since during tests we install and unistall distros multiple times, that seems to be quite possible.