distro.GUID() should not fail due name casing
Yeah, but that's not what happens:

> go test -tags=gowslmock -run '^TestGUID$'

--- FAIL: TestGUID (0.00s)
    --- FAIL: TestGUID/Success_with_a_real_distro (0.00s)
        distro_test.go:337:
                Error Trace:    D:/GoWSL/distro_test.go:337
                Error:          Received unexpected error:
                                could not obtain GUID of WSLTESTING_TESTGUID_4094334523459432065: distro does not exist
                Test:           TestGUID/Success_with_a_real_distro
                Messages:       could not obtain GUID
FAIL
exit status 1
FAIL    github.com/ubuntu/gowsl 0.287s