TestDistroState shall not diverge due distro name casing
Nor anything that relies on the distro.State()

Well, that's not the case. We're reporting distros we don't find in the registry or command line output as non registered, but we are not finding them because we are case sensitive, when we shouldn't be.

go test -tags=gowslmock -run '^TestDistroState$'

--- FAIL: TestDistroState (0.03s)
    distro_test.go:585: Setup: Registering "wsltesting_TestDistroState_6119492318850881343"
    distro_test.go:585: Setup: Distro "wsltesting_TestDistroState_6119492318850881343" registered
    --- FAIL: TestDistroState/Real_distro_is_stopped (0.00s)
        distro_test.go:652:
                Error Trace:    D:/GoWSL/distro_test.go:652
                Error:          Not equal:
                                expected: "Stopped"
                                actual  : "NotRegistered"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Stopped
                                +NotRegistered
                Test:           TestDistroState/Real_distro_is_stopped
                Messages:       distro.State() does not match expected value
    --- FAIL: TestDistroState/Real_distro_is_running (0.03s)
        distro_test.go:652:
                Error Trace:    D:/GoWSL/distro_test.go:652
                Error:          Not equal:
                                expected: "Running"
                                actual  : "NotRegistered"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Running
                                +NotRegistered
                Test:           TestDistroState/Real_distro_is_running
                Messages:       distro.State() does not match expected value
FAIL
exit status 1
FAIL    github.com/ubuntu/gowsl 0.377s